### ISSUE TITLE
Invert State not implemented?

### ISSUE THREAD

**Issue by rene54321** [pdegeus/openhab2-addons#1]
Hi,

some of my sensors coming up with the wrong state. In the oh1 binding an inverted state was implmented. Is this also available for this binding?

regards René

**Comment by pdegeus** [comment]
Hi René,
Thanks for your feedback. I didn't implement the inverted state yet.
I'll take a look when I have some spare time.
Pepijn

**Comment by pdegeus** [comment]
I've just added support for the invert tag. A new build is available at https://dl.dvelop.nl/oh-imperihome/. I expect the binding will be merged into the openHAB distribution in the next few days.
