### ISSUE TITLE
DevGenericSensor not working

### ISSUE THREAD

**Issue by mgf909** [pdegeus/openhab2-addons#2]
Hi,

Ive had some time to look closer into my issue with DevGenericSensor causing Imperihome to not load the system.

I believe the bug is that there is an additional "value" being added to the data.

{"key":"Value","value":**{"value":**"Clear"}}]}

Taking the json data from my OH1's Imperihab for the same Weather Condition item  it returns this:
`{"id":"Weather_Condition","name":"Weather Condition","type":"DevGenericSensor","room":"Weather","params":[
		{"key":"Value","value":"Clear"}
	]},
	`

Whereas using your addon, it returns:
`{"id":"f7b0044b0e0b4ddf6bfb94861381d9b7704a00bb","name":"Condition","room":"284af3e8882bbc45760521be2f100a2d104ff5d8","type":"DevGenericSensor","inverted":false,"params":[{"key":"Value","value":{"value":"Clear"}}]}`

As you can see there is extra braces and value bits ;-)
Hope this helps....and thanks again.

**Comment by pdegeus** [comment]
Thanks for providing details on the issue! This way it was a quick fix.
New build available at https://dl.dvelop.nl/oh-imperihome/.

**Comment by mgf909** [comment]
Confirmed working - thanks again!
I guess u also should update the read.me table to say it also now supports String data types.
DevGenericSensor    Generic sensor (any value)  Yes Number,String

Thanks again.

I also need DevLock but no hurry.
