### ISSUE TITLE
Multiple DevGenericSensor in same room

### ISSUE THREAD

**Issue by gottsman** [pdegeus/openhab2-addons#3]
I have a "room" full of Roku devices where I capture what app is running. Currently, Imperihome is only showing the first one in the list. Here is my .items file.

```
String RokuSE  "Roku SE: [%s]" ["iss:type:DevGenericSensor", "iss:room:Roku", "iss:label:RokuSE"] <television> (Rokus)
String Roku3  "Roku 3: [%s]" ["iss:type:DevGenericSensor", "iss:room:Roku", "iss:label:Roku3"] <television> (Rokus)
String Roku4  "Roku 4 Premiere: [%s]" ["iss:type:DevGenericSensor", "iss:room:Roku", "iss:label:Roku4"] <television> (Rokus)
```

**Comment by pdegeus** [comment]
Hi gottsman, thanks for reporting. You seem to have to order of your lines wrong; the tags should go after the groups ("(Rokus)"). If you have channels linked to your items elsewhere, the tags go before them.
Example:
   ` Color   L_Bedroom             "Bedroom"          <colorlight>   (gLights,gLights_SLP)   ["iss:room:Bedroom", "iss:type:DevRGBLight"] { channel="hue:0210:0011223344:bulb2:color" }`

If that doesn't help, please provide a debug log of your openHAB startup with these items active.

**Comment by gottsman** [comment]
Bingo! That fixed it... From the docs, I didn't see more than one of the same device type per room. Wasn't sure if it that was my issue. 

Thanks for your help.
